export const GET_SOLICITUDES = 'GET_SOLICITUDES';
export const GET_ASIGNACIONES = 'GET_ASIGNACIONES';
export const GET_PANEL1 = 'GET_PANEL1';
export const GET_ACTA1 = 'GET_ACTA1';
export const GET_DETALLE_ACTA1 = 'GET_DETALLE_ACTA1';
export const GET_DETALLE_SOL = 'GET_DETALLE_SOL';
export const GET_ESTUDIANTES = 'GET_ESTUDIANTES';
export const GET_DATEACTA = 'GET_DATEACTA';
export const GET_MESACTA = 'GET_MESACTA';
export const GET_ANIOACTA = 'GET_ANIOACTA';
export const GET_TACTA = 'GET_TACTA';
export const GET_SDIA = 'GET_SDIA';
export const GET_HORADEFENSA = 'GET_HORADEFENSA';
export const GET_ACTUALFECHA = 'GET_ACTUALFECHA';
export const GET_ACTUALFECHASOL = 'GET_ACTUALFECHASOL';
export const GET_HISTORIALESTUDIANTE = 'GET_HISTORIALESTUDIANTE';

export const GET_ACTUAL_CORRELATIVO = 'GET_ACTUAL_CORRELATIVO';

//docentes
export const GET_DOCENTE = 'GET_DOCENTE';

export const GET_DOCENTE_P1 = 'GET_DOCENTE_P1';
